### ISSUE TITLE
Completed trades return 0 and NaN Rolimons value and demand

### ISSUE THREAD

**Issue by Remarkablo** [ItsProyal/RoPro#2]
![image](https://user-images.githubusercontent.com/101928439/159118182-9dce2849-d62f-4a10-8b0a-6c3a6f161259.png)

**Comment by ItsProyal** [comment]
i do not trade so i have no real way to test anything however im pretty sure its the same way in normal ropro, i looked in there discord and people with actual subscriptions have the same problem. tldr: this is most likely an actual ropro or rolimon problem

**Comment by Remarkablo** [comment]
alright then, ill just wait until they fix it then
